# Generated by Django 4.1.7 on 2023-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteor', '0002_exteors_alter_articles_options_articles_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteors',
            name='json_file',
            field=models.JSONField(null=True, verbose_name='Схема'),
        ),
    ]
