# Generated by Django 4.1.7 on 2023-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteor', '0007_alter_exteors_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exteors',
            options={'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AddField(
            model_name='exteors',
            name='common',
            field=models.BooleanField(default=False, verbose_name='Общая'),
        ),
    ]
