# Generated by Django 4.1.7 on 2023-04-07 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_exteors_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exteors',
            name='alias',
            field=models.CharField(blank=True, max_length=50, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='exteors',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exteors',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='exteors',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='exteors',
            name='schema',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
