# Generated by Django 4.1.7 on 2023-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_exteors_alias_exteors_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exteors',
            options={'ordering': ['date_update'], 'verbose_name': 'Имя + Схема', 'verbose_name_plural': 'Имена + Схемы'},
        ),
    ]
