# Generated by Django 4.1.7 on 2023-04-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_exteors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exteors',
            options={'verbose_name': 'Имя + Схема', 'verbose_name_plural': 'Имена + Схемы'},
        ),
    ]
