# Generated by Django 4.1.7 on 2023-04-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_exteors_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exteors',
            unique_together={('name', 'schema')},
        ),
    ]
